# Redis configuration file

# Enable KeySpace Notifications for Expired events
# E: Keyevent events, published with __keyevent@<db>__ prefix.
# x: Expired events (events generated every time a key expires).
notify-keyspace-events "Ex"

# Default port
port 6379

# Bind to all interfaces (Careful in production!)
bind 0.0.0.0

# Memory management
# maxmemory 256mb
# maxmemory-policy allkeys-lru

# Persistence settings (Optional)
appendonly yes
appendfilename "appendonly.aof"
